on: [pull_request]

jobs:
  # https://github.com/kha7iq/pingme-action
  pingme-job:
    if: false # disable this job
    runs-on: ubuntu-latest
    name: PingMe
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ping me On
        uses: kha7iq/pingme-action@v1
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNELS: ${{ secrets.TELEGRAM_CHANNELS }}
          TELEGRAM_TITLE: 'Refrence: ${{ github.ref }}'
          TELEGRAM_MESSAGE: 'A new ${{ github.event_name }} has been opened from ${{ github.head_ref }}'
        
        with:
          # Chose the messaging platform. 
          # slack / telegram / rocketchat / teams / pushover / discord / email
          service: telegram

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - 'tip'
          - '1.19'
          - '1.18'
          - '1.17'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test ./...
