on: [pull_request]

jobs:
  # https://github.com/kha7iq/pingme-action
  pingme-job:
    if: false # disable this job
    runs-on: ubuntu-latest
    name: PingMe
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ping me On
        uses: kha7iq/pingme-action@v1
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNELS: ${{ secrets.TELEGRAM_CHANNELS }}
          TELEGRAM_TITLE: 'Refrence: ${{ github.ref }}'
          TELEGRAM_MESSAGE: 'A new ${{ github.event_name }} has been opened from ${{ github.head_ref }}'
        
        with:
          # Chose the messaging platform. 
          # slack / telegram / rocketchat / teams / pushover / discord / email
          service: telegram
